# Generated by Django 2.2.1 on 2019-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
