# Generated by Django 2.2.1 on 2019-06-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(blank=True, default='Apparently, this user prefers to keep an air of mystery about them.', max_length=150, null=True),
        ),
    ]
