# Generated by Django 2.2.1 on 2019-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=True, max_length=255),
        ),
    ]
