# Generated by Django 2.2.1 on 2019-05-31 07:36

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190530_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=blogs.models.author_document_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.author_blog_images),
        ),
    ]
