# Generated by Django 2.2.1 on 2019-05-31 07:51

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190531_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=False, upload_to=blogs.models.author_blog_images),
            preserve_default=False,
        ),
    ]
