# Generated by Django 2.2.1 on 2019-06-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190531_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=True, max_length=255, unique=True),
        ),
    ]
