# Generated by Django 2.2.1 on 2019-06-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190601_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
